In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [3]:
# resize the ndarray
a = np.array([[1,2,3], [4,5,6]])
a.shape = (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# reshape
a = np.array([[1,2,3], [4,5,6]])
b = a.reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# range
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
# reshaping a one dimenational array
a = np.arange(24)
# now reshaping
b = a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [10]:
x = np.array([1,2,3,4,5], dtype=np.int8)
x.itemsize

1

In [12]:
y = np.array([1,2,3,4,5], dtype=np.float)
y.itemsize

8

In [13]:
z = np.array([1,2,3,4,5], dtype=np.float32)
z.itemsize

4

In [14]:
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

__np.empty It creates an uninitialized array of specified shape and dtype__<br>
__numpy.empty(shape, dtype = float, order = 'C')__

In [15]:
np.empty([3,2], dtype=int)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
np.empty([3,2], dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [20]:
np.empty([3,2], dtype=int)

array([[                  0, 7310593858020254331],
       [4049070531863519844, 3554518997966860589],
       [3329624924132489776, 2475350538773935412]])

__np.zeros Returns a new array of specified size, filled with zeros.__<br>
__numpy.zeros(shape, dtype = float, order = 'C')__

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [25]:
# custom type
np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i8')])

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i8')])

In [26]:
# similarly - array of five ones. Default dtype is float 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [28]:
np.ones([2,3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

__np.asarray - This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.__<br>
__numpy.asarray(a, dtype = None, order = None)__

In [32]:
x = [1,2,3,4]
np.asarray(x)

array([1, 2, 3, 4])

In [31]:
np.asarray(x, dtype=float)

array([1., 2., 3., 4.])

In [34]:
x = [(1,2,3), (4,5)]
np.asarray(x)

array([(1, 2, 3), (4, 5)], dtype=object)

__np.fromiter - This function builds an ndarray object from an iterable object. A new one-dimentional array is returned by this function__ <br>
__numpy.fromiter(iterable, dtype, count = -1)__

In [35]:
l = range(5)

In [37]:
np.fromiter(l, dtype=int)

array([0, 1, 2, 3, 4])

In [38]:
# iterator list
itl = iter(l)

In [40]:
np.fromiter(itl)

TypeError: Required argument 'dtype' (pos 2) not found

In [41]:
np.fromiter(itl, dtype=float)

array([0., 1., 2., 3., 4.])