In [1]:
import numpy as np

Array Preocessing normal python array v/s numpy array

In [2]:
%%timeit
temp_list = range(100000)
temp_list1 = [x*2 for x in temp_list]

5.05 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%%timeit
temp_arr = np.arange(100000)
temp_arr1 = temp_arr * 2

279 µs ± 1.28 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
# ndarray can be created for regular python list or tupple
mylist = [2,5,8,15,25]
array = np.array(mylist)

In [5]:
array

array([ 2,  5,  8, 15, 25])

In [6]:
type(array)

numpy.ndarray

In [7]:
np.arange(100000) * 2

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [8]:
array.shape

(5,)

In [9]:
array[0]

2

In [10]:
array[0:3]

array([2, 5, 8])

In [11]:
array.dtype

dtype('int64')

__ndim - Number of array dimensions__

Data type Object (dtype) in NumPy Python
Every ndarray has an associated data type (dtype) object. This data type object (dtype) informs us about the layout of the array. This means it gives us information about :

- Type of the data (integer, float, Python object etc.)
- Size of the data (number of bytes)
- Byte order of the data (little-endian or big-endian)
- If the data type is a sub-array, what is its shape and data type.

In [12]:
array.ndim

1

In [13]:
a = np.array(111)
b = np.array([1,2,3])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[1,2,3], [4,5]])

In [14]:
a.ndim, b.ndim, c.ndim, d.ndim # d is still 1??? because of dtype

(0, 1, 2, 1)

In [15]:
# Here the dtype of d is 'O' hence the ndim is 1 (i,e) 'O' means python Object
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('O'))

In [16]:
# It means "a python object", i.e. not one of the builtin scalar types supported by numpy.
np.array([object()]).dtype

dtype('O')

In [17]:
# Size of an array - Here it eveluates the each item in the array
a.size, b.size, c.size, d.size

(1, 3, 6, 2)

In [18]:
# dtype can be mentioned while creating an array
array2 = np.array(mylist, dtype=np.float)
array2

array([ 2.,  5.,  8., 15., 25.])

In [19]:
array2.dtype

dtype('float64')

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
# creating a 5 x 3 muti dimentional array
marray = np.arange(15).reshape(5,3)

In [22]:
marray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
marray.ndim

2

In [24]:
np.array([[1,2]]).ndim

2

In [25]:
np.array([[1,2], [4,5]]).ndim

2

In [26]:
np.array([[1,2], [4,5], [8,9,10]]).ndim

1

In [27]:
np.array([[[1,2], [3,4]], [7,8]])

array([[list([1, 2]), list([3, 4])],
       [7, 8]], dtype=object)

In [28]:
np.arange(15).reshape(3, 5).ndim

2

In [29]:
ndim_array = np.random.rand(2,2,3,4)

In [30]:
ndim_array.ndim

4

In [31]:
ndim_array

array([[[[0.9316104 , 0.54627459, 0.33784666, 0.15700585],
         [0.8354796 , 0.34539284, 0.61041412, 0.65587862],
         [0.75805751, 0.07484798, 0.04581055, 0.72430856]],

        [[0.35134217, 0.71524894, 0.56260162, 0.93114912],
         [0.18555087, 0.14263771, 0.53064091, 0.71435098],
         [0.75540097, 0.13458574, 0.44082661, 0.62401454]]],


       [[[0.36500289, 0.44671882, 0.68487044, 0.59490209],
         [0.05447257, 0.89551202, 0.05191093, 0.02398174],
         [0.06168225, 0.75685036, 0.16304841, 0.20854721]],

        [[0.25288961, 0.64957697, 0.36278169, 0.03918946],
         [0.67638776, 0.69468398, 0.49663983, 0.44826679],
         [0.96200063, 0.92962876, 0.77656074, 0.4577908 ]]]])

In [32]:
# multi dimentional array
marray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
marray.ndim, marray.shape, marray.size

(2, (5, 3), 15)

In [34]:
# ravel function helps to flattens array
marray.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
marray.ravel().reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
marray.shape

(5, 3)

__Array Basic Operation__

In [37]:
# multiplying a scalr and ndarray
marray*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [38]:
# inplace change there are certain operations that will modify the object inplace
marray += 10

In [39]:
marray

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [40]:
marray > 15

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
arr_A = np.array([[2,3], [4,5]])
arr_B = np.array([[6,7], [8,9]])

In [42]:
arr_A

array([[2, 3],
       [4, 5]])

In [43]:
arr_B

array([[6, 7],
       [8, 9]])

In [44]:
# operates element wise
arr_A * arr_B

array([[12, 21],
       [32, 45]])

In [45]:
# dot is used for matrix multiplication
# dot product of two arrays
arr_A.dot(arr_B)

array([[36, 41],
       [64, 73]])

In [46]:
arr_A

array([[2, 3],
       [4, 5]])

In [47]:
arr_B

array([[6, 7],
       [8, 9]])

In [48]:
np.dot(arr_A, arr_B)

array([[36, 41],
       [64, 73]])

__Array Slicing__

In [49]:
marray[0]

array([10, 11, 12])

In [50]:
marray[0, 1]

11

In [51]:
# : all items in that 1 to 3
marray[:, 1:3]

array([[11, 12],
       [14, 15],
       [17, 18],
       [20, 21],
       [23, 24]])

In [52]:
marray[:, 1:5]

array([[11, 12],
       [14, 15],
       [17, 18],
       [20, 21],
       [23, 24]])

In [53]:
marray[:, 0:1]

array([[10],
       [13],
       [16],
       [19],
       [22]])

In [60]:
ndim_array

array([[[[0.9316104 , 0.54627459, 0.33784666, 0.15700585],
         [0.8354796 , 0.34539284, 0.61041412, 0.65587862],
         [0.75805751, 0.07484798, 0.04581055, 0.72430856]],

        [[0.35134217, 0.71524894, 0.56260162, 0.93114912],
         [0.18555087, 0.14263771, 0.53064091, 0.71435098],
         [0.75540097, 0.13458574, 0.44082661, 0.62401454]]],


       [[[0.36500289, 0.44671882, 0.68487044, 0.59490209],
         [0.05447257, 0.89551202, 0.05191093, 0.02398174],
         [0.06168225, 0.75685036, 0.16304841, 0.20854721]],

        [[0.25288961, 0.64957697, 0.36278169, 0.03918946],
         [0.67638776, 0.69468398, 0.49663983, 0.44826679],
         [0.96200063, 0.92962876, 0.77656074, 0.4577908 ]]]])

In [64]:
ndim_array[:, :, :, 0:2]

array([[[[0.9316104 , 0.54627459],
         [0.8354796 , 0.34539284],
         [0.75805751, 0.07484798]],

        [[0.35134217, 0.71524894],
         [0.18555087, 0.14263771],
         [0.75540097, 0.13458574]]],


       [[[0.36500289, 0.44671882],
         [0.05447257, 0.89551202],
         [0.06168225, 0.75685036]],

        [[0.25288961, 0.64957697],
         [0.67638776, 0.69468398],
         [0.96200063, 0.92962876]]]])

In [63]:
ndim_array.shape

(2, 2, 3, 4)

In [81]:
# https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html
ndim_array[:1,  :, :1, :]

array([[[[0.9316104 , 0.54627459, 0.33784666, 0.15700585]],

        [[0.35134217, 0.71524894, 0.56260162, 0.93114912]]]])

In [85]:
ndim_1 = np.random.rand(2,3,3,5)

In [92]:
# acndim_array.reshape(2,3)

ValueError: cannot reshape array of size 48 into shape (2,3)

In [93]:
# Can be reshaped to different dimention
ndim_array.reshape(6,8)

array([[0.9316104 , 0.54627459, 0.33784666, 0.15700585, 0.8354796 ,
        0.34539284, 0.61041412, 0.65587862],
       [0.75805751, 0.07484798, 0.04581055, 0.72430856, 0.35134217,
        0.71524894, 0.56260162, 0.93114912],
       [0.18555087, 0.14263771, 0.53064091, 0.71435098, 0.75540097,
        0.13458574, 0.44082661, 0.62401454],
       [0.36500289, 0.44671882, 0.68487044, 0.59490209, 0.05447257,
        0.89551202, 0.05191093, 0.02398174],
       [0.06168225, 0.75685036, 0.16304841, 0.20854721, 0.25288961,
        0.64957697, 0.36278169, 0.03918946],
       [0.67638776, 0.69468398, 0.49663983, 0.44826679, 0.96200063,
        0.92962876, 0.77656074, 0.4577908 ]])

__Splitting of arrays__

In [94]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [95]:
x1, x2, x3 = np.split(x, [3, 5])

How it works is
- arry[:3]
- arry[3:5]
- arry[5:]

In [96]:
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))