In [1]:
import numpy as np

__np.arange - This function returns an ndarray object containing evenly spaced values within a given range__ <br>
__numpy.arange(start, stop, step, dtype)__

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [4]:
# start, stop, step parameters
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

__np.linspace - This function is similar to arange() function. In this function instead of step size, the number of evenly spaced values between the intervals is specified__ <br>
__numpy.linspace(start, stop, num, endpoint, retstep, dtype)__

In [5]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [6]:
np.linspace(10, 20, 5, endpoint=False)

array([10., 12., 14., 16., 18.])

In [7]:
np.linspace(1, 2, 5, retstep=True)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

__np.logspace - This function returns a ndarray object that contains the numbers that are evenly spaced on a log scale. start and stop endpoints of the scale are indeicies of the base__
__numpy.logspace(start, stop, num, endpoint, base, dtype)__

In [8]:
np.logspace(1.0, 2.0, num=10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [9]:
np.logspace(1, 10, num=10, base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])